---
- hosts: webservers
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Loome public_html kataloog user_ile
      file:
        path=/home/user/public_html
        owner=user
        group=user
        mode=0755
        state=directory
    - name: Lubame userdir mod
      apache2_module: name=userdir state=present
    - name: Apache2 serverile alglaadimine (restart)
      service:
        name: apache2
        state: restarted
    - name: Kopeerime index.html faili user-ile kodus_public_html kataloogi
      copy:
        src: /var/www/html/index.html
        dest: /home/user/public_html/
        remote_src: yes
        owner: user
        group: user
    - name: user index.html redigeerimine
      lineinfile: dest=/home/user/public_html/index.html regexp="Apache2 Debian Default Page" line="TIIDU JA TEEDU LEHEKYLG" state=present
    - name: Alglaadimine Apache2
      service:
        name: apache2
        state: restarted
